//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimovitalRazor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MimovitalRazor.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索対象のデータが存在しません。.
        /// </summary>
        public static string SYS01E001 {
            get {
                return ResourceManager.GetString("SYS01E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索に失敗しました。システム管理者まで問い合わせください。.
        /// </summary>
        public static string SYS01E002 {
            get {
                return ResourceManager.GetString("SYS01E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個人IDを入力してください。.
        /// </summary>
        public static string SYS01W001 {
            get {
                return ResourceManager.GetString("SYS01W001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個人IDは半角数字13桁で入力してください。.
        /// </summary>
        public static string SYS01W002 {
            get {
                return ResourceManager.GetString("SYS01W002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報取得に失敗しました。システム管理者まで問い合わせください。.
        /// </summary>
        public static string SYS02E001 {
            get {
                return ResourceManager.GetString("SYS02E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示に必要なパラメータが不足しています。システム管理者までお問い合わせください。.
        /// </summary>
        public static string SYS02E002 {
            get {
                return ResourceManager.GetString("SYS02E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当画面は個人IDの異常データのみを集計した情報を表示しています。検索一覧画面の検索結果とは関係がありません。.
        /// </summary>
        public static string SYS02I001 {
            get {
                return ResourceManager.GetString("SYS02I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報取得に失敗しました。システム管理者まで問い合わせください。.
        /// </summary>
        public static string SYS03E001 {
            get {
                return ResourceManager.GetString("SYS03E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示に必要なパラメータが不足しています。システム管理者までお問い合わせください。.
        /// </summary>
        public static string SYS03E002 {
            get {
                return ResourceManager.GetString("SYS03E002", resourceCulture);
            }
        }
    }
}
